"""Add the image_url

Revision ID: cdc438bc5b7e
Revises: e47ac6a08393
Create Date: 2025-08-05 09:09:34.833245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc438bc5b7e'
down_revision: Union[str, Sequence[str], None] = 'e47ac6a08393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beaches', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beaches', 'image_url')
    # ### end Alembic commands ###
