"""Add Region Column

Revision ID: e47ac6a08393
Revises: cff845578c2b
Create Date: 2025-08-05 02:26:14.379629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e47ac6a08393'
down_revision: Union[str, Sequence[str], None] = 'cff845578c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beaches', sa.Column('regions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beaches', 'regions')
    # ### end Alembic commands ###
